services:
  ai-app:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8501:8501
    environment:
      - GOOGLE_API_KEY
      - LOCAL_BASE_URL
      - REMOTE_MODEL_NAME
      - LOCAL_MODEL_NAME
    depends_on:
      - ollama
  ollama:
    # Build the custom image instead of pulling the default one
    build:
      context: .
      dockerfile: Dockerfile.ollama
    volumes:
      # This saves the downloaded models outside the container
      # so you don't have to re-download on every start
      - ollama_data:/root/.ollama
    ports:
      - 11434:11434

# Define the volume to persist the model data
volumes:
  ollama_data: